name: 🚨 Zizmor Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize ]
  schedule:
    - cron: 0 0 * * *
  workflow_call:

jobs:
  zizmor:
    name: zizmor latest via PyPI
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - name: Run zizmor 🌈
        run: uvx zizmor --format sarif . > zizmor.sarif
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if SARIF file contains findings
        id: check_sarif
        run: |
          FINDINGS_COUNT=$(jq '[.runs[].results[]] | length' zizmor.sarif)
          echo "Findings count: $FINDINGS_COUNT"
          if [ "$FINDINGS_COUNT" -eq 0 ]; then
            echo "no_findings=true" >> $GITHUB_ENV
          else
            echo "no_findings=false" >> $GITHUB_ENV
          fi

      - name: Convert SARIF to markdown
        if: env.no_findings == 'false'
        run: |
          curl -L -o sarif-to-markdown https://github.com/Antvirf/go-sarif-to-markdown-table/raw/refs/heads/main/bin/sarif-to-markdown-table-linux-amd64
          chmod +x sarif-to-markdown
          cat zizmor.sarif | sarif-to-markdown > results.md

      - name: Generate unique issue title
        if: env.no_findings == 'false'
        id: title
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "title=🔒 Zizmor GHA Report - $TIMESTAMP" >> $GITHUB_OUTPUT

      - name: Create GitHub issue in project-tracker
        if: env.no_findings == 'false'
        run: |
          gh issue create \
            --repo american-swim-team/project-tracker \
            --title "${{ steps.title.outputs.title }}" \
            --body-file results.md \
            --label "🔒 security"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR with SARIF findings
        if: github.event_name == 'pull_request' && env.no_findings == 'false'
        run: |
          gh pr comment ${{ github.event.number }} \
            --body-file results.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

