name: 🚨 Zizmor Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize ]
  schedule:
    - cron: 0 0 * * *
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
      ZIZMOR_ISSUE_TOKEN:
        required: true

jobs:
  zizmor:
    name: zizmor latest via PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Check if the repository belongs to the american-swim-team organization
        run: |
          REPO_OWNER=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)
          if [ "$REPO_OWNER" != "american-swim-team" ]; then
            echo "This workflow is only allowed to run in the american-swim-team organization."
            exit 1
          fi

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - name: Run zizmor 🌈
        run: uvx zizmor --format sarif . > zizmor.sarif
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if SARIF file contains findings
        id: check_sarif
        run: |
          FINDINGS_COUNT=$(jq '[.runs[].results[]] | length' zizmor.sarif)
          echo "Findings count: $FINDINGS_COUNT"
          if [ "$FINDINGS_COUNT" -eq 0 ]; then
            echo "no_findings=true" >> $GITHUB_ENV
          else
            echo "no_findings=false" >> $GITHUB_ENV
          fi

      - name: Convert SARIF to markdown
        if: env.no_findings == 'false'
        run: |
          curl -L -o sarif-to-markdown https://github.com/Antvirf/go-sarif-to-markdown-table/raw/refs/heads/main/bin/sarif-to-markdown-table-linux-amd64
          chmod +x sarif-to-markdown
          cat zizmor.sarif | ./sarif-to-markdown > results.md

      - name: Generate unique issue title
        if: env.no_findings == 'false'
        id: title
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          ISSUE_TITLE="🔒 Zizmor GHA Report for ${GITHUB_REPOSITORY} - $TIMESTAMP"
          echo "ISSUE_TITLE=${ISSUE_TITLE}" >> $GITHUB_ENV

      - name: Create GitHub issue in project-tracker
        if: env.no_findings == 'false'
        run: |
          gh issue create \
            --repo american-swim-team/project-tracker \
            --title "${ISSUE_TITLE}" \
            --body-file results.md \
            --label "🔒 security"
        env:
          GH_TOKEN: ${{ secrets.ZIZMOR_ISSUE_TOKEN }}

